name: flutter_admin_dashboard_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intersperse: ^2.0.0
  recase: ^4.1.0
  responsive_framework: ^1.4.0
  simple_logger: ^1.9.0+3
  two_dimensional_scrollables: ^0.3.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.4

dev_dependencies:
  build_runner: 
  build_verify: 
  flutter_test:
    sdk: flutter
  go_router_builder: 
  pedantic_mono:

flutter:
  uses-material-design: true
